image: Visual Studio 2017

version: 1.1.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: w1QgTKjQb/SRT5RvjLDGRniq5S6HV+otG5MywPqt6J3DwZYcddT+/H4SA/YZx/8y

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU

configuration: Release

build:
  parallel: true  
  project: Mongo.Migration.sln
  publish_wap: true               
  publish_wap_xcopy: true         
  publish_azure: true             
  publish_nuget: true             
  publish_nuget_symbols: true     
  include_nuget_references: true  
  
cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

after_test:
   - ps: .\nuget\pack.ps1
   - cmd: .\post_build.cmd

artifacts:
  - path: Mongo.Migration\bin\Release\net45\Mongo.Migration.dll
    name: Mongo.Migration.dll
  - path: Mongo.Migration\bin\Release\net47\Mongo.Migration.dll
    name: Mongo.Migration.dll
  - path: Mongo.Migration\bin\Release\netstandard2.0\Mongo.Migration.dll
    name: Mongo.Migration.dll
  - path: '**\Mongo.Migration.*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: U9STqjDjIz1j/0PFSPM0sCYt+0WTU3Cx5w1cw06RWIdPeXZUmCq2nScvhimnQ9NH
#  artifact: /.*\.nupkg/